version: "3"

services:
  lectures-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/lecturesDB
      - PORT=3000
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=lecturesDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
